### PR TITLE
catCode/catCave/catHandle id is editable now

### LINKED ISSUE #961: Need the ID to be specified for new values of catCode, catCave, catHandle
The ID field for these tables contains an abbreviation of the `Name` - so it is used in presenting the data.

So, when we `Create` one of the values, we should allow the `id` to be specified.

Also, we should have an `Edit` page, which allows the `id`, `name` and `active` to be edited.

Hmm, editing an `id` after it has been created could cause problems if it has been used as an FK anywhere.  I'm pretty sure SQLite will catch that happening, and throw an error.  We should catch errors from saving an edited one of these and report "Error: potential break to referential integrity. Please obtain database support".

Note: we may need to show a warning like this one: https://github.com/DeepBlueCLtd/RCO/issues/954#issuecomment-1886817936

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #961

### CODE REVIEW

File: src/resources/reference-data/ReferenceDataForm.tsx [hunk 1]
```diff
@@ -143,9 +146,16 @@ export default function ReferenceDataForm(
     name?: string
   }): React.ReactElement => {
     const createRecord = useCustomid()
+    const validName = name ?? ''
+    const resourcesWithListPage = [
```
Comment (IanMayo) [inline src/resources/reference-data/ReferenceDataForm.tsx:150]: we should just declare this constant once, please.

File: src/resources/reference-data/ReferenceDataForm.tsx [hunk 2]
```diff
@@ -201,13 +211,29 @@ const FormContent = ({
...
+    constants.R_CAT_HANDLE,
+    constants.R_DEPARTMENT
+  ]
 
-  const warningTextForId =
-    'Warning: Editing the id of a Department that is in use may lead to data corruption.  The id of a department must not be modified if data has been assigned to that department.'
+  const resourceName =
+    name === constants.R_DEPARTMENT
+      ? 'department'
+      : name === constants.R_CAT_CODE
```
Comment (IanMayo) [inline src/resources/reference-data/ReferenceDataForm.tsx:225]: The strings for `code`, `cave` and `handle` have to come from the `ConfigData`, please.

Comment (TahaKhanAbdalli) [reply src/resources/reference-data/ReferenceDataForm.tsx:225]: Oky let me check.

File: src/resources/reference-data/ReferenceDataForm.tsx (hunk 1 above)
Comment (TahaKhanAbdalli) [reply src/resources/reference-data/ReferenceDataForm.tsx:151]: okay. Sorry I haven't seen this massage before. Let me fix it now. Please confirm you are talking about `const validName = name ?? ''` ?

Comment (IanMayo) [reply src/resources/reference-data/ReferenceDataForm.tsx:151]: No, I mean the array of resource names in `resourcesWithListPage`.  It contains business logic, but is declared several times.

Comment (TahaKhanAbdalli) [reply src/resources/reference-data/ReferenceDataForm.tsx:151]: Oky.

File: src/constants.ts [hunk 3]
```diff
@@ -126,3 +126,10 @@ export const cosmeticLabels = {
   [R_DEPARTMENT]: 'Department',
   [R_PROTECTIVE_MARKING]: 'Protective Marking'
 }
+
```
Comment (IanMayo) [inline src/constants.ts:129]: Oh, I think we've lost a comment from yesterday - probably my mistake.  Fro the `resourcesWithListPage` const, since it is only used in `ReferenceDataForm`, can we declare it in that file?

(happy to discuss...)

**Comment by IanMayo** [comment]
> Sorry @ian, I didn't understand what you are trying to say.

That's ok :-)  Do you remember why we're directing to `list` rather than `show` when we update these 4 resource types?

**Comment by TahaKhanAbdalli** [comment]
> > Sorry @ian, I didn't understand what you are trying to say.
> 
> That's ok :-) Do you remember why we're directing to `list` rather than `show` when we update these 4 resource types?

Alright, Actually, on the show page, it was showing an error. That's why I redirected to the list instead of the show page.

**Review by IanMayo — APPROVED** [review]
Tested and working

File: src/resources/reference-data/ReferenceDataForm.tsx (hunk 2 above)
Comment (IanMayo) [reply src/resources/reference-data/ReferenceDataForm.tsx:218]: Done.

File: src/constants.ts (hunk 3 above)
Comment (IanMayo) [reply src/constants.ts]: Done.
