### PR TITLE
Show empty list and fixed pagination conflicts with recent batches

### LINKED ISSUE #156: Can't add first `Item` to a `Batch`
When the `ItemList` component is empty, we don't have an `Add Item` toolbar button. We don't have a toolbar :-)

image

### PR DESCRIPTION
**Pull request by salony75way**
fixes #156 156

### CODE REVIEW

File: src/components/Recent.tsx [hunk 1]
```diff
@@ -96,6 +96,7 @@ export default function Recent<T>(props: Props<T>): React.ReactElement {
     <RecentCard label={label} resource={resource}>
       <ResourceContext.Provider value={resource}>
         <List
+          storeKey={`recent-${resource}` }
```
Comment (IanMayo) [inline src/components/Recent.tsx:99]: @salony75way - can you clarify what the pagination problem was please?

**Review by IanMayo — APPROVED** [review]

File: src/components/Recent.tsx (hunk 1 above)
Comment (salony75way) [reply src/components/Recent.tsx:99]: List params corresponding to resources are stored to local storage so when we open bathes list after welcome page then the recent batches pagination was applied to batch list and also batches are sorted by descending order.
This was vice versa so just changed the storeKey for recent batches.
