### PR TITLE
save/clone not capturing itemCode, itemCave and itemHandle fixed

### LINKED ISSUE #816: Save/Clone does not capture itemCave, itemCode, itemHandle
A user has added an item to a batch.  They set values for all the `protection` fields.

They pressed `Save/Clone`.  A new item was shown, with the previous values in the protection fields all visible.

They pressed `Save/Clone` a few more times, to create some new cloned items.

Then they went to the batch, and viewed the items. When they drilled down into the `ItemShow` page, only the `Protective Marking" was set, the others weren't.

It _looks-like_ we are correctly populating the form when cloning an existing item, but when we save that form, these new values for `itemCode`, `itemCave` and `itemHandle` are not recognised.

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #816

### CODE REVIEW

File: src/components/ProtectionRefInput.tsx [hunk 1]
```diff
@@ -164,6 +166,7 @@ export default function ProtectionRefInput<
       } else if (id) {
         createRecord(id, selectedData as number[])
       }
+      reset(getValues())
```
Comment (IanMayo) [inline src/components/ProtectionRefInput.tsx:169]: Hello @Taha - could you give me a quick description of what was broken, and how this fix works please?

**Review by IanMayo — APPROVED** [review]
Solution works

File: src/components/ProtectionRefInput.tsx (hunk 1 above)
Comment (TahaKhanAbdalli) [reply src/components/ProtectionRefInput.tsx:169]: `isSubmitSuccessful` was not getting reset after first submission. So, I `reset` the form and set the values that already were there which triggered `isSubmitSuccessful` to turn to true from false.
