### PR TITLE
338 filters added on dispatch and destruction list

### LINKED ISSUE #338: Dispatch list filters
Toggle filter doesn't work with nullable fields.

- Not dispatched (dispatchedAt is undefined/null),
- Receipt not received (receiptReceived  is undefined/null)

**Updated objectve**:
* [ ] introduce "Filters" for dispatches and destructions
* [ ] Introduce "Dispatched", "Not dispatched", "Receipt note pending" toggle filters for dispatches

Related issue: #334

### PR DESCRIPTION
**Pull request by TahaKhanAbdalli**
fixes #338

### CODE REVIEW

**Comment by IanMayo** [comment]
One change: the filter for `pending receipt note` is that `dispatchedAt` is non-null, and `receiptReceived` is null.

So, we only show items that have been sent, but for which receipt note is still awaited.

File: src/components/NullUndefinedFilter.tsx [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+  source: string
+}
+
+const NullUndefinedFilter = (props: Props): React.ReactElement => {
+  const { label, source } = props
+  const { setFilters, displayedFilters, filterValues } = useListContext()
+
+  useEffect(() => {
+    setFilters(
+      {
```
Comment (IanMayo) [inline src/components/NullUndefinedFilter.tsx:16]: we seem to insert `filterValues` twice, below.
